<?php
require_once 'PHPUnit/Util/Filter.php';

PHPUnit_Util_Filter::addFileToFilter(__FILE__);

$content = $this->render($this->content);
require_once 'Zend/Log.php';
require_once 'Zend/Log/Adapter/File.php';
Zend_Log::registerLogger(new Zend_Log_Adapter_File(dirname(__FILE__) . '/view.log'), 'Zend_View_Test');
Zend_Log::log(var_export($content, 1), Zend_Log::LEVEL_DEBUG, 'Zend_View_Test');
Zend_Log::log(var_export(__FILE__, 1), Zend_Log::LEVEL_DEBUG, 'Zend_View_Test');
