<html>
<head>
	<title>Zend_Wildfire Demos and Tests</title>
	<style>
		BODY, TD {
			font-family:verdana,arial,helvetica,sans-serif;
			font-size:11px;		
		}
    DIV.group {
      border: 1px solid gray;
      margin-bottom: 10px;
    }
    DIV.group > DIV.heading {
      font-size: 16px;
      font-weight: bold;
      background-color: lightgray;
      padding: 3px;
      padding-left: 10px;
      padding-right: 10px;
    }
    DIV.group > DIV.body {
      padding: 10px;
    }
	</style>
</head>
<body>

<table border="0" width="100%" height="100%" cellpadding="10" cellspacing="0">
	<tr>
		<td valign="top" nowrap>

			<p><b>General Requirements</b></p>
			<ul>
				<li><a target="_blank" href="http://www.getfirefox.com/">Firefox 3</a></li>
			</ul>
      
      <br/>
      
      <div class="group">
        
        <div class="heading">Zend_Toolbar</div>
  
        <div class="body">
    			<p><b>Additional Requirements</b></p>
    			<ul>
    				<li><a target="_blank" href="http://framework.zend.com/svn/framework/standard/branches/user/dasprid/Zend_Toolbar/extension/">Zend_Toolbar Extension</a></li>
    			</ul>
    
    			<p><b>Instructions</b></p>
    			<p>Click on the links below and look for output in<br>the ZF Toolbar at the bottom of your browser.</p>
  
       		<p><b>Zend_Toolbar</b></p>
    			<ul>
    				<li><a href="Zend-Toolbar/HelloWorld" target="main">Hello World</a></li>
    			</ul>
  			</div>

      </div>      
      
      <div class="group">
        
        <div class="heading">Firebug Integration via <a target="_blank" href="http://www.firephp.org/">FirePHP</a></div>
  
        <div class="body">
    			<p><b>Additional Requirements</b></p>
    			<ul>
    				<li><a target="_blank" href="https://addons.mozilla.org/en-US/firefox/addon/1843">Firebug Extension</a></li>
    				<li><a target="_blank" href="https://addons.mozilla.org/en-US/firefox/addon/6149">FirePHP Extension</a></li>
    			</ul>
    
    			<p><b>Instructions</b></p>
    			<p>Click on the links below and<br>look for output in the Firebug Console.</p>
  
       		<p><b>Zend_Log_Writer_Firebug</b></p>
    			<ul>
    				<li><a href="Zend-Log-Writer-Firebug/TestLogging" target="main">Test Logging</a></li>
    				<li><a href="Zend-Log-Writer-Firebug/TestErrorController" target="main">Test Error Controller</a></li>
    				<li><a href="Zend-Log-Writer-Firebug/TestLargeMessage" target="main">Test Large Message</a></li>
    				<li><a href="Boot/Zend-Log-Writer-Firebug/TestDocExample.php?Example=WithController" target="main">Test Doc Example (With Controller)</a></li>
    				<li><a href="Boot/Zend-Log-Writer-Firebug/TestDocExample.php?Example=WithoutController" target="main">Test Doc Example (Without Controller)</a></li>
    			</ul>
    			<p><b>Zend_Db_Profiler_Firebug</b></p>
    			<ul>
    				<li><a href="Zend-Db-Profiler-Firebug/TestLogging" target="main">Test Logging</a></li>
    				<li><a href="Zend-Db-Profiler-Firebug/TestMultipleDatabases" target="main">Test Multiple Databases</a></li>
    				<li><a href="Boot/Zend-Db-Profiler-Firebug/TestDocExample.php?Example=WithController" target="main">Test Doc Example (With Controller)</a></li>
    				<li><a href="Boot/Zend-Db-Profiler-Firebug/TestDocExample.php?Example=WithoutController" target="main">Test Doc Example (Without Controller)</a></li>
    			</ul>
    			<p><b>Zend_Wildfire_Plugin_FirePhp</b></p>
    			<ul>
    				<li><a href="Zend-Wildfire-Plugin-FirePhp/TestGroups" target="main">Test Groups</a></li>
    			</ul>
  			</div>

      </div>

		</td>
		<td valign="top" width="100%">
			<iframe name="main" width="100%" height="100%" border="1"></iframe>
		</td>
	</tr>
</table>

</body>
</html>